version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/xanzy/go-gitlab
    versions:
    - 0.42.0
    - 0.43.0
    - 0.44.0
    - 0.45.0
    - 0.46.0
  - dependency-name: github.com/spf13/cobra
    versions:
    - 1.1.2
